name: Deploy website on push
on: 
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      with: 
        ref: main
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14' 
    - name: npm install
      run: npm install
    - name: tsc
      uses: alexthemaster/action-build-typescript@v1.3.1
    - name: Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: 92.63.169.233
        username: github
        password: ${{ secrets.ftp_password }}
        remote_path: var_www/portfolio-new/
