name: Deploy website on push
on: 
  push:
    branches:
    - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      with: 
        ref: main
    - name: Install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Compile TypeScript
      run: tsc
    - name: Compile SCSS
      run: sass src:public/build --style compressed
    - name: Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: 92.63.169.233
        username: github
        password: ${{ secrets.ftp_password }}
        remote_path: var_www/portfolio-new/
